[package]
name = "blockchain_Scratch"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web="4"
chrono="0.4"
serde={version = "*", features = ["derive"]}
serde_json="1.0"
sha2="0.9"
tokio={version = "*", features = ["full"]}